version: '3.9'

services:
  django:             
    image: django-docker:0.0.1
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app        # Mount current directory to /app in container
    working_dir: /app # Set working dir inside container
    command: sh -c "python3 manage.py runserver 0.0.0.0:8000"
