# Generated by Django 4.1 on 2022-09-09 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=20)),
                ('city_area', models.IntegerField()),
                ('city_population', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('State_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('number_of_cities', models.IntegerField()),
                ('number_of_schools', models.IntegerField()),
                ('number_of_stadiums', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town_name', models.CharField(max_length=20)),
                ('town_code', models.IntegerField()),
                ('town_population', models.IntegerField()),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='town_city', to='app.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_state', to='app.state'),
        ),
    ]
