# Generated by Django 4.1.1 on 2022-09-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_state_state_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='state_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/media'),
        ),
    ]
