# Generated by Django 5.1.7 on 2025-03-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_state_state_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cities_visited', models.ManyToManyField(related_name='tourists', to='app.city')),
            ],
        ),
    ]
